---
engines:
  rubocop:
    enabled: true
    exclude_paths:
      - config/engines.yml
      - config/bootstrap.php
      - public/index.php
      - src/Kernel.php
      - config/bootstrap.php
      - public/js/jquery.js
  duplication:
    enabled: true
    exclude_paths:
      - config/engines.yml
      - config/bootstrap.php
      - public/index.php
      - src/Kernel.php
      - config/bootstrap.php
      - public/js/jquery.js
  metric:
    enabled: true
    exclude_paths:
      - config/engines.yml
      - config/bootstrap.php
      - public/index.php
      - src/Kernel.php
      - config/bootstrap.php
      - public/js/jquery.js
  coverage:
    enabled: true
    exclude_paths:
      - config/engines.yml
      - config/bootstrap.php
      - public/index.php
      - src/Kernel.php
      - config/bootstrap.php
      - public/js/jquery.js
languages:
  css:
    extensions:
      - '-css.resource'
exclude_paths:
  - '.bundle/**'
  - 'spec/**/*'
  - 'benchmarks/**/*'
  - '**.min.js'
  - '**/tests/**'

